INSERT INTO users
VALUES
(1, 'Oliwier', 'Chrzanowski', 34, 'Wolin'),
(2, 'Wirginia', 'Staniszewski', 64, 'Rychwał'),
(3, 'Beniamin', 'Marszałek', 32, 'Zawidów'),
(4, 'Herman', 'Szafrański', 31, 'Jastrowie'),
(5, 'Filip', 'Bielski', 30, 'Międzyrzecz'),
(6, 'Tekla', 'Kozłowski', 29, 'Debrzno'),
(7, 'Hanna', 'Czech', 40, 'Opoczno'),
(8, 'Karolina', 'Rosiak', 52, 'Skoczów'),
(9, 'Martyna', 'Zajączkowski', 30, 'Siemianowice Śląskie'),
(10, 'Grzegorz', 'Urbańczyk', 50, 'Środa Wielkopolska'),
(11, 'Stanisław', 'Grochowski', 54, 'Jabłonowo Pomorskie'),
(12, 'Anatol', 'Kogut', 44, 'Władysławowo'),
(13, 'Herman', 'Grzesik', 34, 'Andrychów'),
(14, 'Lucja', 'Zielonka', 49, 'Sokółka'),
(15, 'Jerzy', 'Matysiak', 65, 'Wodzisław Śląski'),
(16, 'Judyta', 'Mrozek', 41, 'Pniewy'),
(17, 'Ansgary', 'Zdunek', 33, 'Boguszów-Gorce'),
(18, 'Eleonora', 'Bukowski', 63, 'Stronie Śląskie'),
(19, 'Maja', 'Piotrowicz', 22, 'Kluczbork'),
(20, 'Lilia', 'Sienkiewicz', 37, 'Pakość'),
(21, 'Antoni', 'Malec', 28, 'Dębno'),
(22, 'Mojżesz', 'Płonka', 45, 'Świątniki Górne'),
(23, 'Roderyk', 'Lesiak', 34, 'Grybów'),
(24, 'Zachariasz', 'Knapik', 60, 'Józefów (powiat otwocki)'),
(25, 'Helena', 'Górny', 26, 'Pilzno'),
(26, 'Arkadiusz', 'Zabłocki', 44, 'Podkowa Leśna'),
(27, 'Archibald', 'Polak', 25, 'Giżycko'),
(28, 'Żaneta', 'Banach', 46, 'Buk'),
(29, 'Witalis', 'Kamiński', 62, 'Gostyń'),
(30, 'Laura', 'Kołodziejczyk', 32, 'Gościno'),
(31, 'Eustracjusz', 'Surma', 63, 'Olsztyn'),
(32, 'Dina', 'Dubiel', 57, 'Gryfino'),
(33, 'Ewa', 'Kucharczyk', 39, 'Łaskarzew'),
(34, 'Gertruda', 'Podgórski', 36, 'Rzepin'),
(35, 'Michalina', 'Urban', 60, 'Lesko'),
(36, 'Edyta', 'Jędrzejewski', 36, 'Blachownia'),
(37, 'Ewelina', 'Krzemiński', 52, 'Rychwał'),
(38, 'Szymon', 'Wnuk', 47, 'Kartuzy'),
(39, 'Andżelika', 'Piątkowski', 69, 'Wschowa'),
(40, 'Miron', 'Frankowski', 49, 'Obrzycko'),
(41, 'Eleonora', 'Motyka', 38, 'Wołomin'),
(42, 'Oleg', 'Krawczyk', 22, 'Mikołajki'),
(43, 'Bertrand', 'Kasprzyk', 24, 'Kożuchów'),
(44, 'Angela', 'Nawrocki', 51, 'Warta'),
(45, 'Lilia', 'Bieńkowski', 45, 'Sułkowice'),
(46, 'Dorota', 'Bielecki', 51, 'Brusy'),
(47, 'Jerzy', 'Mielczarek', 18, 'Toszek'),
(48, 'Witalis', 'Stefaniak', 28, 'Sieradz'),
(49, 'Róża', 'Kaszuba', 32, 'Drawno'),
(50, 'Arnold', 'Kaźmierczak', 70, 'Szlichtyngowa'),
(51, 'Edmund', 'Małek', 26, 'Iłża'),
(52, 'Ernest', 'Trzciński', 35, 'Ostrów Mazowiecka'),
(53, 'Reginald', 'Grudzień', 47, 'Milicz'),
(54, 'Teodor', 'Miller', 68, 'Chełmża'),
(55, 'Salwator', 'Lenart', 62, 'Świętochłowice'),
(56, 'Reginald', 'Banaś', 20, 'Szczawno-Zdrój'),
(57, 'Cezary', 'Rudzki', 49, 'Kolno'),
(58, 'Ryszard', 'Bożek', 41, 'Połaniec'),
(59, 'Jadwiga', 'Bielecki', 56, 'Brzeg'),
(60, 'Artur', 'Osiński', 30, 'Łomianki'),
(61, 'Cyrus', 'Wójcicki', 57, 'Brzeszcze'),
(62, 'Henryk', 'Frąckowiak', 44, 'Woźniki'),
(63, 'Julia', 'Piątek', 15, 'Łasin'),
(64, 'Anastazja', 'Piasecki', 66, 'Kobyłka'),
(65, 'Leon', 'Iwanowski', 18, 'Tomaszów Lubelski'),
(66, 'Liza', 'Kaczmarek', 22, 'Brwinów'),
(67, 'Tobiasz', 'Filipiak', 21, 'Kleczew'),
(68, 'Beatrycze', 'Marszałek', 16, 'Lubraniec'),
(69, 'Józefina', 'Świerczyński', 66, 'Wyrzysk'),
(70, 'Teodor', 'Lech', 56, 'Sulechów'),
(71, 'Seweryn', 'Florczak', 54, 'Sułkowice'),
(72, 'Gerazym', 'Ostrowski', 49, 'Mogilno'),
(73, 'Alfred', 'Bednarczyk', 53, 'Przecław'),
(74, 'Melania', 'Koza', 45, 'Krzanowice'),
(75, 'Eugenia', 'Baranowski', 30, 'Czerniejewo'),
(76, 'Lea', 'Mazurek', 17, 'Ślesin'),
(77, 'Penelopa', 'Ziętek', 44, 'Nowy Tomyśl'),
(78, 'Estera', 'Kostecki', 24, 'Skarszewy'),
(79, 'Edyta', 'Smoliński', 21, 'Chełmno'),
(80, 'Miron', 'Kaszuba', 34, 'Myszków'),
(81, 'Pantaleon', 'Zaborowski', 50, 'Kalety'),
(82, 'Serafina', 'Szymczak', 45, 'Oleszyce'),
(83, 'Magnus', 'Gajewski', 68, 'Cieszanów'),
(84, 'Gabriel', 'Kurek', 48, 'Wyszków'),
(85, 'Konstantyn', 'Szwarc', 23, 'Kudowa-Zdrój'),
(86, 'Dionizy', 'Cholewa', 69, 'Opole'),
(87, 'Terencjusz', 'Dudzik', 46, 'Łosice'),
(88, 'Walentyn', 'Filipowicz', 26, 'Zakliczyn'),
(89, 'Agata', 'Baranowski', 63, 'Radom'),
(90, 'Eustracjusz', 'Furman', 51, 'Piastów'),
(91, 'Serafin', 'Więckowski', 70, 'Muszyna'),
(92, 'Ruta', 'Rudziński', 53, 'Kcynia'),
(93, 'Natalia', 'Michalak', 66, 'Kęty'),
(94, 'Irma', 'Górecki', 30, 'Złoczew'),
(95, 'Wirginia', 'Dębski', 51, 'Zgierz'),
(96, 'Klaudia', 'Włodarski', 22, 'Krynica Morska'),
(97, 'Galfryd', 'Ratajczak', 16, 'Rogoźno'),
(98, 'Mojżesz', 'Palacz', 29, 'Błonie'),
(99, 'Nina', 'Kaczorowski', 44, 'Olszyna'),
(100, 'Ksenia', 'Sokół', 25, 'Cedynia');